### ISSUE TITLE
Little design «issue»

### ISSUE THREAD

**Issue by tmos** [yosko/jotter#4]
Hi,
Just a little advice (not really an issue…) :
In the dropdown menu (where you can select and change the current notebook), notebooks titles are in text-align:center, it can confuse the user : at the first look if you have one long and one short title, it seems like a hierarchy in notebooks.

May seems a little bit precise, but i personally spent 5 minutes to look how I made a child notebook… but it wasn't me ಠ_ರೃ

Good work, Jotter is veeeeeery usefuul :+1:

**Comment by yosko** [comment]
I think I see what you mean. I thought this centering was a bit confusing but did it anyway, and now that you mention it...

I'll take it into account for the next version (which takes it time, by-the-way, cause there is a lot to do ^^' ). I'll align left the text in the dropdown, and maybe choose a slightly different way to show the items "select a notebook" and "create a new notebook" so that it becomes more clear that there is no "level" of notebooks (not yet sure how, though)...

**Comment by tmos** [comment]
Maybe for the «create a new notebook» you can add it to the main toolbar at the very top left of the interface ?

**Comment by yosko** [comment]
The thing is I'd rather avoid adding to much buttons (as to keep Jotter clearer), especially if I can't find an obvious icon for this specific task. And mentionning it in a textual way inside this dropdown seemed better to me.

I don't know yet, but I'll think about it...

**Comment by yosko** [comment]
I'll align left the text in the dropdown, and I think i'll simply use an optgroup for the existing notebooks. This way, the dropdown would look more like:
- &raquo; select a notebook
- **Load a notebook**
  - Notebook 1
  - Notebook 2
  - Notebook 3
- &raquo; Create a new notebook

**Comment by tmos** [comment]
Seems pretty good :+1:

**Comment by yosko** [comment]
Fixed in 58ec59877d
